on:
  push:
    paths:
      - apps/python-api/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin 050752638165.dkr.ecr.us-east-1.amazonaws.com

      - name: Build, tag, and push image
        run: |
          IMAGE_TAG=v$(date +%s)
          IMAGE_URI=050752638165.dkr.ecr.us-east-1.amazonaws.com/python-api:$IMAGE_TAG

          docker build -t $IMAGE_URI ./apps/python-api
          docker push $IMAGE_URI

          sed -i "s|image: .*|image: $IMAGE_URI|g" apps/python-api/deployment.yaml

      - name: Commit updated deployment.yaml
        run: |
          git config user.name "github-actions"
          git config user.email "ci@github.com"
          git add apps/python-api/deployment.yaml
          git commit -m "CI: Update image tag to latest build"
          git push origin main
