name: Build and Deploy Python API

on:
  push:
    paths:
      - apps/python-api/**
      - .github/workflows/ci.yaml

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: python-api
  IMAGE_BASE: 050752638165.dkr.ecr.us-east-1.amazonaws.com/python-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Generate image tag
        id: tag
        run: echo "IMAGE_TAG=v$(date +%s)" >> $GITHUB_ENV

      - name: Build and push Docker image with tag and latest
        run: |
          docker build -t $IMAGE_BASE:$IMAGE_TAG -t $IMAGE_BASE:latest ./apps/python-api
          docker push $IMAGE_BASE:$IMAGE_TAG
          docker push $IMAGE_BASE:latest

      - name: Update image tag in deployment.yaml
        run: |
          sed -i "s|image: .*|image: $IMAGE_BASE:$IMAGE_TAG|" apps/python-api/deployment.yaml

      # - name: Commit updated deployment.yaml
      #   env:
      #     GH_PAT: ${{ secrets.GH_PAT }}
      #   run: |
      #     git config user.name "github-actions"
      #     git config user.email "ci@github.com"
      #     git add apps/python-api/deployment.yaml
      #     git diff --cached --quiet || git commit -m "CI: Update image tag to $IMAGE_TAG"
      #     git remote set-url origin https://${GH_PAT}@github.com/${{ github.repository }}
      #     git push origin main
